//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRestApiWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int StudentID { get; set; }
        public string StdName { get; set; }
        public string StdAdress { get; set; }
        public string Course { get; set; }
    }
}
